---
version: "3"

tasks:
  install:
    cmds:
      - "brew install mkdocs-material"

  lint:
    cmds:
      - "pre-commit run --all-files"

  serve:
    cmds:
      - "mkdocs serve"

  build:
    cmds:
      - "mkdocs build --strict"
...
